### ISSUE TITLE
AWS Elasticsearch Service Support - PR's Welcome?

### ISSUE THREAD

**Issue by maxmanders** [github/vulcanizer#89]
My colleague pointed me at this tool, and it looks great! I'd started implementing something similar before finding out about Vulcanizer.

We use AWS' managed service offering of ElasticSearch, AWS Elasticsearch Service. While it exposes the same API as standard ElasticSearch, requests to the AWS service must be [signed using IAM credentials](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html).

Is support for AWS offering something you'd consider supporting? I'd happily try to put together a PR that introduces request signing if the host ends with `amazonaws.com` - but I thought I'd check if that aligned with this project before I tried to implement anything.

**Comment by nickcanz** [comment]
👋 Hi @maxmanders! 

PRs would definitely be welcome! Right now the code isn't organized _great_, but I'd be happy to work with you on a PR to support AWS Elasticsearch Service in a reasonable way. The goal of the project is definitely to try to help with Elasticsearch anywhere it's running 😄

**Comment by nickcanz** [comment]
There is a "builder" function for the HTTP request here, I think this would be the most likely place to add that: https://github.com/github/vulcanizer/blob/db3bbdb535abe1ace149219375bd5153eb556e66/es.go#L389-L425

In terms of parsing the URL, instead I think it would make sense to just make it an explicit configuration option, similar to how basic HTTP auth is set, since it looks like you can [set up custom domains for AWS Elasticsearch](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-customendpoint.html).

Regardless, feel free to open up a PR and we can work through it together 👍

**Comment by maxmanders** [comment]
On reflection, I'm going to close this. I must have misunderstood the AWS documentation. I'm able to use Vulcanizer to interact with AWS Elasticsearch Service without the need for signed requests.
